DirectInput実装
human-osaka-game-2019/The_Destination_Of_Shadow pull request #14
Opened 2019-10-25 09:25 UTC by gotakamikubo

## 元issue
closes #11 

## 作業内容
DirectInputを実装し、キーボードによる操作を可能にする

2019-10-27 10:01 UTC, taishi-matsumura requested changes
修正依頼と質問をいくつか。
質問には回答お願い〜。

2019-10-27 10:01 UTC, taishi-matsumura commented on the_destination_of_shadow/DirectX.cpp
> +			if (curr_diks[i] & mask.NUM)
毎年言ってるのですが、この式が何を意味するのか直感的にわからないです。
関数化した方が良いと思います。
下記の辻野とのやり取りでサンプルコードも書いたので参考にして下さい。
https://github.com/human-osaka-game-2018/StarLight_Line/pull/1#discussion_r234207791
https://github.com/human-osaka-game-2018/StarLight_Line/pull/1#pullrequestreview-176050839

2019-10-27 10:01 UTC, taishi-matsumura commented on the_destination_of_shadow/DirectX.cpp
> +				}
三項演算子使った方がスッキリすると思いますよ。

2019-10-27 10:01 UTC, taishi-matsumura commented on the_destination_of_shadow/DirectX.cpp
> +		for (INT i = 0; i < KEY_MAX; i++)
範囲ベースforとかで書けませんか？

2019-10-27 10:01 UTC, taishi-matsumura commented on the_destination_of_shadow/DirectX.cpp
> +}
別に問題無いのですが、1行関数はヘッダファイルにinlineで書くことが多いです。

2019-10-27 10:01 UTC, taishi-matsumura commented on the_destination_of_shadow/DirectX.cpp
> +		return E_FAIL;
エラーになった場合、どうなるのですか？
呼び出し元を見る限り、戻り値に関係無く処理が進むように見受けられます。

2019-10-27 10:10 UTC, taishi-matsumura commented
@gotakamikubo 
このプルリクがmergeされたタイミングで元issueも閉じちゃっていいのかな？
だったら自動的にそうなるようにコメントに書いておきましょう。

2019-10-27 10:30 UTC, gotakamikubo commented on the_destination_of_shadow/DirectX.cpp
> +		return E_FAIL;
そのまま処理が進み、手動で終了させなくてはいけなくなっているので
エラーになった時、終了するように修正します

2019-10-27 10:38 UTC, gotakamikubo commented on the_destination_of_shadow/DirectX.cpp
> +		return E_FAIL;
修正しました

2019-10-27 10:44 UTC, taishi-matsumura commented on the_destination_of_shadow/DirectX.cpp
> +		return E_FAIL;
確認しました。
他の箇所( `GenerateWindow()` とか)もエラー処理甘いように思うので、機会があれば修正していってください。、

2019-10-27 10:47 UTC, gotakamikubo commented on the_destination_of_shadow/DirectX.cpp
> +}
この関数はこのプルリクで修正しますが他関数は #13 で修正します。

2019-10-27 10:52 UTC, gotakamikubo commented on the_destination_of_shadow/DirectX.cpp
> +}
修正しました

2019-10-27 11:03 UTC, taishi-matsumura commented on the_destination_of_shadow/DirectX.cpp
> +}
了解です。
余談ですが、指摘是正でファイル弄ったついでに最終行に改行入ってるかを確認すると良いですよ。

2019-10-27 11:03 UTC, taishi-matsumura commented on the_destination_of_shadow/DirectX.cpp
> +}
了解です。
余談ですが、指摘是正でファイル弄ったついでに最終行に改行入ってるかを確認すると良いですよ。

2019-10-28 00:07 UTC, gotakamikubo commented on the_destination_of_shadow/DirectX.cpp
> +				}
修修正します

2019-10-28 00:08 UTC, gotakamikubo commented on the_destination_of_shadow/DirectX.cpp
> +			if (curr_diks[i] & mask.NUM)
関数化します

2019-10-28 08:59 UTC, gotakamikubo commented on the_destination_of_shadow/DirectX.cpp
> +			if (curr_diks[i] & mask.NUM)
関数化しました

2019-10-28 08:59 UTC, gotakamikubo commented on the_destination_of_shadow/DirectX.cpp
> +				}
修正しました

2019-10-28 09:00 UTC, gotakamikubo commented on the_destination_of_shadow/DirectX.cpp
> +		for (INT i = 0; i < KEY_MAX; i++)
苦戦しているので後回しにして
別プルリクで修正します

2019-10-29 08:29 UTC, taishi-matsumura commented on the_destination_of_shadow/DirectX.cpp
> +		for (INT i = 0; i < KEY_MAX; i++)
了解です

2019-10-29 08:37 UTC, taishi-matsumura requested changes
@MinoriNakamura もうちょっとお互いにチェックし合って下さい。

2019-10-29 08:37 UTC, taishi-matsumura commented on the_destination_of_shadow/DirectX.cpp
> +	if (curr_diks & mask.NUM)
せっかく関数作ったのに使ってないやん！

2019-10-29 08:37 UTC, taishi-matsumura commented on the_destination_of_shadow/DirectX.cpp
> +KEY_STATE DirectX::GetPrevDik(BYTE curr_diks)
関数名を見ると「previous direct input keyを取得する関数」のようですが、引数で渡されたcurrent direct input keyの先頭ビットをチェックするのですか？
関数名と処理内容が合っていないように思います。

あと、戻り値はboolで良いのでは？で、そうなると関数名が微妙ですね。

2019-10-29 08:37 UTC, taishi-matsumura commented on the_destination_of_shadow/DirectX.cpp
> +	static BYTE prev_diks[KEY_MAX] = { OFF };
配列の初期化のしかた、これで合っていますか？結果オーライなだけでは？
前期にも見たと思いますが、 [この記事](https://tt4cs.hatenadiary.org/entry/20120219/1329636595) をもう一度読み返してみて下さい。

2019-10-29 08:37 UTC, taishi-matsumura commented on the_destination_of_shadow/DirectX.h
>  #endif
改行。

2019-10-29 09:01 UTC, gotakamikubo commented on the_destination_of_shadow/DirectX.cpp
> +KEY_STATE DirectX::GetPrevDik(BYTE curr_diks)
bool型にして関数名をIsSetMostSignificantBitに変更します

2019-10-29 09:02 UTC, gotakamikubo commented on the_destination_of_shadow/DirectX.cpp
> +	if (curr_diks & mask.NUM)
忘れていました修正します

2019-10-29 09:02 UTC, gotakamikubo commented on the_destination_of_shadow/DirectX.h
>  #endif
修正します

2019-10-29 09:03 UTC, taishi-matsumura commented on the_destination_of_shadow/DirectX.cpp
> +KEY_STATE DirectX::GetPrevDik(BYTE curr_diks)
あー、その名前は逆方向ですね。
それだと、その関数を呼び出す人は「キーが押されていたら最上位ビットが立っている」ということを知っていないといけなくなるよね？
それを抽象化するために関数化しているのだから、「最上位ビットが立っているってことはつまりどういうことなのか？」というのを表す名前にすべきです。

2019-10-29 10:02 UTC, gotakamikubo commented on the_destination_of_shadow/DirectX.cpp
> +KEY_STATE DirectX::GetPrevDik(BYTE curr_diks)
わかりました。
関数名はIsPushKeyもしくは、IsPressKeyにします

2019-10-29 10:06 UTC, taishi-matsumura commented on the_destination_of_shadow/DirectX.cpp
> +KEY_STATE DirectX::GetPrevDik(BYTE curr_diks)
はい、そんな感じが良いでしょうね。
で、英語として成立していないので(isもpushもpressも動詞です)、もうちょっと練って下さい。
戸田に相談しても良いと思うよ 😏

2019-10-29 10:25 UTC, gotakamikubo commented on the_destination_of_shadow/DirectX.cpp
> +	static BYTE prev_diks[KEY_MAX] = { OFF };
勘違いをしていました、修正します。

2019-10-29 10:33 UTC, taishi-matsumura commented on the_destination_of_shadow/DirectX.cpp
> +KEY_STATE DirectX::GetPrevDik(BYTE curr_diks)
主語が(thisではなく)keyになるパターンですね。
受動態の疑問文で名前付ければ良いと思いますよ。
中学英語！！

2019-10-29 10:39 UTC, gotakamikubo commented on the_destination_of_shadow/DirectX.cpp
> +KEY_STATE DirectX::GetPrevDik(BYTE curr_diks)
WasKeyPressedはどうでしょうか

2019-10-29 10:43 UTC, taishi-matsumura commented on the_destination_of_shadow/DirectX.cpp
> +KEY_STATE DirectX::GetPrevDik(BYTE curr_diks)
文法的にはOK！けど、「押されていた(今は離されている)か」になってしまうね。
「押されているか」であれば、 `IsKeyPressed()` だと思うよ。
その辺りは関数の意味と照らし合わせて検討して下さい。

あと、こういうのは一人で悩まないこと！！
他の人に相談しながら進めるべきだし、チームメンバは能動的に一緒に考えましょう。

2019-10-29 11:00 UTC, gotakamikubo commented on the_destination_of_shadow/DirectX.cpp
> +	if (curr_diks & mask.NUM)
修正しました

2019-10-29 11:01 UTC, gotakamikubo commented on the_destination_of_shadow/DirectX.cpp
> +KEY_STATE DirectX::GetPrevDik(BYTE curr_diks)
修正しました

2019-10-29 11:01 UTC, gotakamikubo commented on the_destination_of_shadow/DirectX.cpp
> +	static BYTE prev_diks[KEY_MAX] = { OFF };
修正しました

2019-10-29 11:01 UTC, gotakamikubo commented on the_destination_of_shadow/DirectX.h
>  #endif
修正しました

2019-10-29 11:16 UTC, taishi-matsumura reviewed
コピコンと代入演算子の隠蔽までやったのね。ステキ！！

2019-10-29 11:16 UTC, taishi-matsumura commented on the_destination_of_shadow/DirectX.cpp
> +	if (IsKeyPressed(curr_diks)==TRUE)
```suggestion
	if (IsKeyPressed(curr_diks))
```
とするのではなく、if文の中は明示的にTRUEと比較する方針ですか？
であれば、それで揃えて下さいね。

2019-10-29 11:16 UTC, taishi-matsumura commented on the_destination_of_shadow/DirectX.cpp
> +	return (curr_diks & mask.NUM) ? TRUE : FALSE;
こういうパッと見ナゾなコードには、
```suggestion
	// キーが押されているときはcurr_diksの最上位ビットが立っている
	return (curr_diks & mask.NUM) ? TRUE : FALSE;
```
等、コメントしておくと良いと思いますよ。

2019-10-29 11:16 UTC, taishi-matsumura commented on the_destination_of_shadow/DirectX.cpp
> +	}
好みの問題だとは思いますが、elseで括る必要は無いですね。
「`IsKeyPressed(curr_diks)==TRUE` の場合と、そうでない場合を対比させたいんです！」という意図によるコードであればこれで良いでしょう。

2019-10-29 11:16 UTC, taishi-matsumura commented on the_destination_of_shadow/DirectX.cpp
> +	for (int i = 0; i < KEY_MAX; i++)
こんなのこそ、一番単純な範囲ベースforの出番では？
```suggestion
	for (BYTE& prev_dik : prev_diks)
```
で良さそう。
(当然、for文の中身は `prev_dik = OFF;` に変えないとダメですが)

2019-10-29 11:18 UTC, taishi-matsumura approved these changes

2019-10-29 11:18 UTC, gotakamikubo commented on the_destination_of_shadow/DirectX.cpp
> +	if (IsKeyPressed(curr_diks)==TRUE)
後日中村さんと話し合いどちらにするかを決めます

2019-10-29 11:19 UTC, gotakamikubo commented on the_destination_of_shadow/DirectX.cpp
> +	return (curr_diks & mask.NUM) ? TRUE : FALSE;
了解です

2019-10-29 11:19 UTC, taishi-matsumura commented
まだWIP付いていますが、松村としてはapproveしておきます。

@MinoriNakamura 
あとヨロシク！！
mergeボタン押す前に、コミットメッセージの整理はしてもらってねー

2019-10-29 11:20 UTC, gotakamikubo commented on the_destination_of_shadow/DirectX.cpp
> +	for (int i = 0; i < KEY_MAX; i++)
修正します

2019-10-29 11:35 UTC, taishi-matsumura commented on the_destination_of_shadow/DirectX.cpp
> +	if (IsKeyPressed(curr_diks)==TRUE)
ちなみに、昔のC言語は言語としてboolが無かったので「TRUEが0と定義されているかも」という可能性がありました。(成功やエラー無しのときに `return 0;` と書くことが多い名残)
そのせいで「TRUE/FALSEと比較しましょう」なんていうルールを見たことありますが、今のCやC++では冗長なので、提示したコードの方が良いと思いますよ。

また、C/C++ではif文の条件式は非boolでも可能なので `if(curr_dik & 0x80)` なんてコードが書けるわけですが(JavaやC#ではコンパイル通りません)、これを「C/C++の便利機能なのでOK」とするか「明示的に `if((curr_dik & 0x80) != 0x00)` と書くべき」とするかは議論の余地がありますね。

2019-11-01 08:00 UTC, merged