[WIP]Xinput を実装する
human-osaka-game-2019/The_Destination_Of_Shadow pull request #2
Opened 2019-10-16 06:06 UTC by gotakamikubo

[ ] バイブレーションを使用できるようにす

 [ ] ボタン入力

 [ ] スティック操作

2019-10-17 16:58 UTC, taishi-matsumura reviewed
質問です。回答お願いします。

2019-10-17 16:58 UTC, taishi-matsumura commented on the_destination_of_shadow/DirectX.cpp
> +#pragma comment (lib,"Xinput.lib")
`#pragma comment (lib, "xxxxx.lib")` はソースコードに直接書けて便利なのですが、
* リンカに指定する内容(＝コンパイル時に関係無い内容)がソースコード内に出てくる
* "#pragma XXXX" 自体がコンパイラ独自のコマンド

の二点から、初学者が使うべきでは無いと思っています。
「これでいきます！」と言うのであれば、この方法を採る理由・根拠が欲しいです。

2019-10-17 17:08 UTC, taishi-matsumura requested changes
修正お願いしまーす

2019-10-17 17:08 UTC, taishi-matsumura commented on the_destination_of_shadow/DirectX.cpp
> +	if (dwResult != ERROR_SUCCESS) m_is_connect = FALSE;
不細工ですね。三項演算子を使ってみてはいかが？

2019-10-17 17:08 UTC, taishi-matsumura commented on the_destination_of_shadow/DirectX.h
> +	BOOL m_is_connect;
『接続されているか？』という意味のフラグですよね？であれば英語としておかしいです。

2019-10-17 17:08 UTC, taishi-matsumura commented on the_destination_of_shadow/DirectX.h
> +	XINPUT_VIBRATION XinputVibration;
メンバ変数の命名規則はどうなっていますか？
prefixの有無や、Upper/Lower camelが入り乱れているのでなんとかして下さい。

2019-10-17 17:08 UTC, taishi-matsumura commented on the_destination_of_shadow/DirectX.h
> +	XINPUT_STATE XinputState;
全てのメンバがpublicだったらstructで良いのでは？
けど、こいつはstructにしては機能を持ち過ぎだと思うのでclassにすべきだと思いますので、カプセル化して下さい。

2019-10-17 17:08 UTC, taishi-matsumura commented on the_destination_of_shadow/DirectX.h
> +	HRESULT UpdateControllerState();
publicなメンバにはdoxgenコメントを書いて下さい。

2019-10-17 17:10 UTC, taishi-matsumura commented
各featureブランチはdevelopブランチにmergeする方針ですか？
であれば、masterだけではなくdevelopブランチも保護すべきですね。
設定お願いします。

2019-10-17 18:17 UTC, taishi-matsumura requested changes

2019-10-17 18:17 UTC, taishi-matsumura commented on the_destination_of_shadow/DirectX.cpp
> +	(dwResult == ERROR_SUCCESS) ? m_is_connected = TRUE : m_is_connected = FALSE;
三項演算子使うなら
```suggestion
	m_is_connected = (dwResult == ERROR_SUCCESS) ? TRUE : FALSE;
```
かな。

2019-10-17 18:21 UTC, taishi-matsumura requested changes
定数は、書き換え可能な普通のメンバ変数と区別できるような命名規則にしておいた方が良いと思いますよ。

2019-10-17 18:21 UTC, taishi-matsumura commented on the_destination_of_shadow/DirectX.h
> +	static const INT m_max_key = 256;
定数は、修正前の方が良いと思います。

2019-10-17 18:24 UTC, gotakamikubo commented on the_destination_of_shadow/DirectX.h
> +	static const INT m_max_key = 256;
了解です
学校で中村さんと話し合います

2019-10-17 18:24 UTC, taishi-matsumura commented on the_destination_of_shadow/DirectX.h
> +	KEY_STATE m_key_state[256];
「メンバ変数はprefixとして `m_` を付与し、それ以後スネーク」ということですね？
悪くは無いですが、あまり見ない形であることは知っておいて下さい。
C++の場合は `m_KeyState` とか `m_keyState` が一般的かな。

2019-10-17 18:27 UTC, gotakamikubo commented on the_destination_of_shadow/DirectX.cpp
> +#pragma comment (lib,"Xinput.lib")
プロパティを開くよりも早く確認、追加ができると思いこの方法を取っていました
修正します

2019-10-17 18:30 UTC, taishi-matsumura commented on the_destination_of_shadow/DirectX.cpp
> +	return S_OK;
常に `S_OK` を返すのであれば、戻り値の意味無くいですか？

2019-10-17 18:38 UTC, taishi-matsumura commented on the_destination_of_shadow/DirectX.cpp
> +#pragma comment (lib,"Xinput.lib")
めんどくさいと思いますが、今はプロパティを開いて設定する方法に慣れておく方が良いと思います。
2年生になった頃にはリンクするlibを指定している意味や方法もわかっていると思うので、 `#pragma comment(lib, "xxxxx.lib")` も解禁して良いと思います。

2019-10-17 18:41 UTC, taishi-matsumura commented on the_destination_of_shadow/DirectX.cpp
> +	m_is_connected = (XInputGetState(0, &XinputState) == ERROR_SUCCESS) ?  TRUE :  FALSE;
`？` の前に関数呼び出しが入るのはやり過ぎ(読み辛い)気がするので、個人的には `XInputGetState()` の戻り値を一旦変数に格納する方が好きですが、まぁ良いでしょう。

2019-10-18 09:30 UTC, taishi-matsumura requested changes
doxygenコメント書いたのなら、ちゃんとドキュメントが生成されることまで確認しましょう。
『doxygenっぽいコメント』なら、書く意味無いです！ 💩

2019-10-18 09:30 UTC, taishi-matsumura commented on the_destination_of_shadow/DirectX.h
> +	//! デバイスの作成
引数のコメント書かないと、doxygenかけたときにエラー出ませんか？

2019-10-18 09:44 UTC, taishi-matsumura commented on the_destination_of_shadow/DirectX.h
>  class DIRECTX
ファイル名は `DirectX.h` で、他のクラスも `Key` とか `Mesh` とかなのに、こいつは `DIRECTX` なの？

2019-10-19 04:22 UTC, taishi-matsumura requested changes
doxygenコメントに関するコミットとのことなので、コメントについての指摘です。

2019-10-19 04:22 UTC, taishi-matsumura commented on the_destination_of_shadow/DirectX.h
> +	* @param (*FilePath)
`@param` の後ろは `()` で囲む必要無いです

2019-10-19 04:22 UTC, taishi-matsumura commented on the_destination_of_shadow/DirectX.h
> +	* @param (*FilePath)
ポインタ型の変数の `*` ですが、型名と仮引数のどちらに付けるか、[MSDN](https://docs.microsoft.com/en-us/windows/win32/api/d3d9/nf-d3d9-idirect3d9-createdevice) を参考にしてみてはいかがでしょうか。

2019-10-19 04:22 UTC, taishi-matsumura commented on the_destination_of_shadow/DirectX.h
> +	* @brief ウィンドウの初期設定
引数のコメント無いよ

2019-10-19 04:22 UTC, taishi-matsumura commented on the_destination_of_shadow/DirectX.h
> +class Key
classやenum等、自作の型にはコメント書きましょう。

2019-10-19 04:22 UTC, taishi-matsumura commented on the_destination_of_shadow/DirectX.h
>  #define WINDOW_HEIGHT 1080
定数にもコメント入れるんじゃないの？

2019-10-19 04:27 UTC, taishi-matsumura requested changes
クラス名について。

2019-10-19 04:27 UTC, taishi-matsumura commented on the_destination_of_shadow/DirectX.h
> +class Mash
`Mash` って何？typoですか？

2019-10-19 04:27 UTC, taishi-matsumura commented on the_destination_of_shadow/DirectX.h
> +class DirectX
`doxygenコメントの追加` のcommitに、 `クラス名の修正` を含めないで下さい。
reviewerに負担が掛かります。
SRPはcommitにも適用しましょう。

2019-10-21 04:14 UTC, taishi-matsumura requested changes
どう直したいのかがサッパリわからん…

2019-10-21 04:14 UTC, taishi-matsumura commented on the_destination_of_shadow/DirectX.h
> +	const INT MESK_NUM = 0x80;
`mash` なのか `mesh` なのか `mask` なのか、どれ？？

2019-10-21 04:16 UTC, taishi-matsumura reviewed
これはXInputの対応と関係無いので別Issue切ってやるべきでしたね。
次回からヨロシク。

2019-10-21 04:24 UTC, taishi-matsumura reviewed
先の指摘に返信する形で「 `mask` が正しいです。修正します」みたいな一言で良いのでレスしましょう。
次回からヨロシク。

2019-10-21 04:29 UTC, taishi-matsumura reviewed
クラス名そのままの情報が変数名に含まれているので、冗長な気がします。
`GamePadDeadZone` の方も同様ですが、`GamePadDeadZone.LEFT` とかで意味がわからなくなるのであれば、クラス名がマズいのでしょうね。

いずれも、再度検討してみて下さい。

2019-10-21 04:29 UTC, taishi-matsumura commented on the_destination_of_shadow/DirectX.h
> +	const INT m_WINDOW_HEIGHT = 1080;
`WIDTH` `と `HEIGHT` でじゅうぶんでは？

2019-10-21 04:32 UTC, gotakamikubo commented on the_destination_of_shadow/DirectX.h
> +	const INT m_WINDOW_HEIGHT = 1080;
class名がWindowSizeなのにWINDOWを定数につけるのは冗長でした
修正します

2019-10-21 04:57 UTC, gotakamikubo commented
残りの指摘は別のissueで修正します

2019-10-21 05:02 UTC, MinoriNakamura commented
レビューを完了し、
これにてpull requestを閉じる。

2019-10-21 05:03 UTC, taishi-matsumura reviewed
> レビューを完了し、
> これにてpull requestを閉じる。

mergeしてないのに閉じたらあかんやん。
ってか、mergeしたら閉じられるよ。

2019-10-21 05:03 UTC, taishi-matsumura commented on the_destination_of_shadow/DirectX.h
> +	* @param hWnd
```suggestion
	* @param hWnd ウィンドウハンドル
```
のように、引数の説明も書いてね。

2019-10-21 05:05 UTC, taishi-matsumura commented
doxygenコメントの修正が終わったら、コミット整理(並べ替えたり、分けたり、纏めたり、コメントにissueのID書いたり)してforce pushしてください。
確認後、mergeします。

2019-10-21 05:10 UTC, taishi-matsumura commented
@gotakamikubo このプルリクでのコミットは全部 #1 についてのものないですよね？
であれば、これらのコミットメッセージ全てに `#1` と書かれているべきですね。
`rebase -i` 使って、「reword」でメッセージ修正して下さい。

2019-10-21 05:40 UTC, taishi-matsumura approved these changes

2019-10-21 05:40 UTC, gotakamikubo commented on the_destination_of_shadow/DirectX.h
> +	const INT m_WINDOW_HEIGHT = 1080;
修正しました

2019-10-21 05:40 UTC, merged

2019-10-21 05:41 UTC, taishi-matsumura commented
話が発散してきたので、とりあえずこのプルリクは承認してmergeしておきます。
XInput以外の課題は別途issueを切って対応お願いしまーす