[WIP]オブジェクトクラスを作成
human-osaka-game-2019/The_Destination_Of_Shadow pull request #27
Opened 2019-11-02 05:27 UTC by gotakamikubo

## 元issue
closes #26 
## 作業

- [ ] オブジェクトクラスを作成

- [ ] CharcterBaseクラスにオブジェクトクラスを継承させる

2019-11-02 18:32 UTC, taishi-matsumura requested changes
getter多過ぎるのが気になります。
「Tell, don't ask」を心掛けて下さい。

2019-11-02 18:32 UTC, taishi-matsumura commented on the_destination_of_shadow/Character.h
> +class CharacterBase:public Object
体裁の話ですが、 `:` の前後にスペース入れた方が良いと思いますよ。

2019-11-02 18:32 UTC, taishi-matsumura commented on the_destination_of_shadow/Character.h
> +
ここには改行入れる方針ですか？

2019-11-02 18:32 UTC, taishi-matsumura commented on the_destination_of_shadow/Draw.h
> +	VOID Draw(Object object, DOUBLE degree = 0.0f);
クラス名が名詞なので `DrawTex::Draw()` なんていう妙ちくりんな名前になるんだと思います。
クラス名、もうちょっと良い名前にできませんか？

2019-11-02 18:32 UTC, taishi-matsumura commented on the_destination_of_shadow/Object.h
> +
アクセス指定子の下の空白行の有無、統一して下さい。

2019-11-02 18:32 UTC, taishi-matsumura commented on the_destination_of_shadow/Object.h
> +	inline FLOAT GetTvHeight() { return m_tv_height; }
getter多過ぎ問題。

2019-11-02 18:42 UTC, gotakamikubo commented on the_destination_of_shadow/Object.h
> +
中村さんと話し合って決めます

2019-11-02 18:45 UTC, gotakamikubo commented on the_destination_of_shadow/Draw.h
> +	VOID Draw(Object object, DOUBLE degree = 0.0f);
単純にTextureにしようと思います

2019-11-02 18:45 UTC, gotakamikubo commented on the_destination_of_shadow/Character.h
> +class CharacterBase:public Object
了解です

2019-11-02 18:53 UTC, gotakamikubo commented on the_destination_of_shadow/Object.h
> +	inline FLOAT GetTvHeight() { return m_tv_height; }
自分でも気持ち悪いと思っているのですがgetterを使用しなければDraw関数を使用できないんです。
DrawTexクラスの中身がこのクラスに移動してくれればましにはなると思うのですが…

2019-11-03 06:50 UTC, taishi-matsumura commented on the_destination_of_shadow/Object.h
> +	inline FLOAT GetTvHeight() { return m_tv_height; }
逆じゃない？
tu/tv等はそのテクスチャの情報なのだから、Playerとかのオブジェクトではなく「Playerが持っているTexture」が知っていれば済むように思います。

2019-11-03 14:33 UTC, taishi-matsumura requested changes
クラスの責務分担と依存関係がおかしいんだと思います。
ざっくりしたイメージですが、下記のような感じになるのでは？
* [クラス図](http://bit.ly/2CabHgY)
* [シーケンス図](http://bit.ly/2WC97Kh)

2019-11-03 14:33 UTC, taishi-matsumura commented on the_destination_of_shadow/Draw.cpp
> +		{object.GetX()						,object.GetY() + object.GetYHeight(),0,1,color,object.GetTu()					   ,object.GetTv() + object.GetTvHeight()},
引数を減らそうとしてこのような作りになったのだと思いますが、Objectクラスを渡してもらって中をほじくり返すというのは良くないですね。
Object(或いはその派生クラス)がTextureのインスタンスを保持する形にして、Texture生成時にそれ以後変わらないもの(例えば左上のtu/tv等)を設定してやれば良いのでは？
Texture側はそれをメンバとして保持しておき、 `Draw()` では描画時に変わる可能性のあるもの(右側のtuとか？)を渡して貰えば良いと思います。alpha値なんかはデフォルト引数にできそうですね。

で、中島ほどextremeになる必要は無いですが、tu・tvやx・yは構造体で固めてしまえば引数は減らせると思いますよー

2019-11-03 14:33 UTC, taishi-matsumura commented on the_destination_of_shadow/Draw.h
> +#include"Object.h"
依存関係がおかしいと思います。
Playerクラス等がTextureクラスを利用するのは理解できますが、TextureクラスがObjectを知っているのは良くないと思いますよー

2019-11-04 07:20 UTC, gotakamikubo commented on the_destination_of_shadow/Draw.h
> +	VOID Draw(Object object, DOUBLE degree = 0.0f);
修正しました

2019-11-04 07:24 UTC, gotakamikubo commented on the_destination_of_shadow/Draw.cpp
> +		{object.GetX()						,object.GetY() + object.GetYHeight(),0,1,color,object.GetTu()					   ,object.GetTv() + object.GetTvHeight()},
了解です

2019-11-04 07:25 UTC, gotakamikubo commented on the_destination_of_shadow/Draw.h
> +#include"Object.h"
修正します

2019-11-04 07:28 UTC, taishi-matsumura commented on the_destination_of_shadow/Main.cpp
> +Texture texture;
そろそろ、この辺のグローバル変数も片付けていこう。
こういうのを放ったらかしにしてると「誰が誰を生成して」とか「誰が誰に依存していて」とかがあやふやになって、結果スパゲティになります。実際、なってきてるよね〜

2019-11-04 07:29 UTC, taishi-matsumura commented on the_destination_of_shadow/Draw.h
> +	VOID Draw(Object object, DOUBLE degree = 0.0f);
オッケーです👌

2019-11-04 08:44 UTC, taishi-matsumura reviewed
今のコードでビルド通りますか？
例えば今回のように「TextureクラスのインスタンスをObjectクラスに移動」とかした際は、それに関係する部分も修正してビルド通る状態を維持しながら作業しないとぐちゃぐちゃになりますよ〜

2019-11-04 09:08 UTC, gotakamikubo commented
実際にぐちゃぐちゃになってしまったのでHardResetして、細かく修正、コミットします

2019-11-05 06:24 UTC, gotakamikubo commented on the_destination_of_shadow/Object.h
> +
アクセス指定子の下には空白行有りで統一します

2019-11-05 06:25 UTC, gotakamikubo commented on the_destination_of_shadow/Character.h
> +class CharacterBase:public Object
修正しました

2019-11-05 07:23 UTC, gotakamikubo commented on the_destination_of_shadow/Draw.h
> +#include"Object.h"
修正しました

2019-11-05 07:25 UTC, gotakamikubo commented on the_destination_of_shadow/Main.cpp
> +Texture texture;
issueを作成し、そこで作業します

2019-11-05 07:27 UTC, gotakamikubo commented on the_destination_of_shadow/Draw.h
> +#include"Object.h"
修正しました

2019-11-05 08:37 UTC, taishi-matsumura commented on the_destination_of_shadow/Main.cpp
> +Texture texture;
了解です👌

2019-11-05 08:37 UTC, taishi-matsumura commented on the_destination_of_shadow/Object.h
> +
了解です👌

2019-11-05 08:40 UTC, taishi-matsumura commented on the_destination_of_shadow/Object.h
> +
了解です。
で、アクセス指定子の上には改行入れないのね…
違和感しか無いけど、それで統一するのなら良いでしょう👌

2019-11-05 08:47 UTC, taishi-matsumura commented on the_destination_of_shadow/Draw.cpp
> +		{xy_coordinate.m_x							,xy_coordinate.m_y							,0,1,color,uv_coordinate.m_tu							,uv_coordinate.m_tv							 },
読みづらくないですか？
下記のような説明的変数を作った方が見易いと思いますが、いかが？
```
	FLOAT left = xy_coordinave.m_x;
	FLOAT right = left + xy_coordinate.m_x_size;
```

2019-11-05 08:49 UTC, taishi-matsumura commented on the_destination_of_shadow/Draw.h
> +	FLOAT m_y_size;
座標を表す構造体なのにサイズが入っているのは違和感ありますが、まぁ良いでしょう。
けど、 `width` と `height` で良くない？

2019-11-05 08:56 UTC, gotakamikubo commented on the_destination_of_shadow/Draw.cpp
> +		{xy_coordinate.m_x							,xy_coordinate.m_y							,0,1,color,uv_coordinate.m_tu							,uv_coordinate.m_tv							 },
自分も長くて読みづらい、変数名の修正がめんどくさいと思っていました。
そのような形に修正します。

2019-11-05 09:20 UTC, gotakamikubo commented on the_destination_of_shadow/Draw.cpp
> +		{xy_coordinate.m_x							,xy_coordinate.m_y							,0,1,color,uv_coordinate.m_tu							,uv_coordinate.m_tv							 },
xy座標は説明的変数で見やすくしたのですが、uv座標もそうすべきなのでしょうか。
xy座標はそうしたのにuv座標はそのままというのは違和感を感じてしまいますし、
だからといってuv座標の説明的変数を作ると計8個と多く感じてしまいます。

2019-11-05 11:18 UTC, taishi-matsumura commented on the_destination_of_shadow/Draw.cpp
> +		{xy_coordinate.m_x							,xy_coordinate.m_y							,0,1,color,uv_coordinate.m_tu							,uv_coordinate.m_tv							 },
その感覚、very goodです！！ 👌 
そういうときは「目的は何か？」に立ち返ると良いと思いますよ。
「xy座標だけで十分だよね」ってなるならそれでいいのでは？

僕なら関数化するとか、CustomVertexクラスみたいなのを作るけどねー。

なんにせよ、非常に良い感覚だと思います！！

2019-11-05 17:07 UTC, taishi-matsumura reviewed
「直した方が良いですよ」というアドバイスです。

2019-11-05 17:07 UTC, taishi-matsumura commented on the_destination_of_shadow/Game.cpp
> +	player.texture.LoadTexture("../Texture/player.png", PLAYER);
ここまでやったのなら、 `Texture#LoadTexture()` を掘るのではなく、 `Player#Load()` みたいなメソッド作ってその中でやったらいいのになぁと思います。

2019-11-05 17:07 UTC, taishi-matsumura commented on the_destination_of_shadow/Game.cpp
> +	player.texture.Draw(player.GetXyCoordinate());
`Texture#LoadTexture()` に関する指摘と同様です。
「Objectクラス＝描画されるもの」なのであれば、 `Object#Draw()` を作ってあげたらいいのになぁと。

2019-11-05 17:07 UTC, taishi-matsumura commented on the_destination_of_shadow/Object.h
> +	XyCoordinate GetXyCoordinate() { return xy_coordinate; }
そのPRで新規追加したmethodなら、constメンバ関数にできるのであればしてしまいましょう〜
そのPRに関係無いmethodに関しては、別途issue作ってやるなり、そのクラスを弄るタイミングでやるなりすれば良いと思います。

2019-11-05 17:23 UTC, taishi-matsumura reviewed
五月雨ですみません。

2019-11-05 17:23 UTC, taishi-matsumura commented on the_destination_of_shadow/Draw.cpp
> +VOID Texture::Animetion(INT * flamecount, INT count, FLOAT * tu, FLOAT * tv, FLOAT split_tu, FLOAT split_tv, FLOAT start_tu, FLOAT start_tv, FLOAT finish_tu, FLOAT finish_tv)
tu/tvの両方向にアニメーションすることってあるんですか？
どちらか片方なのであれば、tu方向とtv方向それぞれのアニメーション関数に分けた方が良いと思います。
この辺りはatlasの作りやゲームの仕様に依りますね。

2019-11-05 17:23 UTC, taishi-matsumura commented on the_destination_of_shadow/Draw.cpp
> +VOID Texture::LoadTexture(const CHAR * file_name, INT TEX)
ポインタの `*` の前後両方にスペース入れるパターンは見ないですねぇ。

`VOID Texture::LoadTexture(const CHAR* file_name, INT TEX)` 或いは
`VOID Texture::LoadTexture(const CHAR *file_name, INT TEX)` で統一して下さい。

2019-11-05 17:23 UTC, taishi-matsumura commented on the_destination_of_shadow/Draw.cpp
> +DOUBLE Texture::to_Rad(DOUBLE degree)
なんかこれだけ他と命名が合わないですね。

```suggestion
DOUBLE Texture::ToRadian(DOUBLE degree)
```
かな。

2019-11-05 17:23 UTC, taishi-matsumura commented on the_destination_of_shadow/Draw.cpp
>  	return degree * atan(1.0)* 4.0 / 180.0;
中島もarctan使う話をしていましたが、もっとシンプルで良いように思うのですが…
これにする理由ってあるんですか？元ネタサイト等あれば教えて下さい。

2019-11-05 17:23 UTC, taishi-matsumura commented on the_destination_of_shadow/Game.h
> +	VOID Loading();
これだけ動名詞になっている理由は？

2019-11-05 17:23 UTC, taishi-matsumura commented on the_destination_of_shadow/Draw.h
> +enum TEX
コメント入れましょう。

2019-11-05 17:23 UTC, taishi-matsumura commented on the_destination_of_shadow/Draw.h
> +struct XyCoordinate
これもコメント。

2019-11-05 17:23 UTC, taishi-matsumura commented on the_destination_of_shadow/Draw.h
> +struct UvCoordinate
コメント。

2019-11-05 17:23 UTC, taishi-matsumura commented on the_destination_of_shadow/Character.h
> +	virtual VOID Move() = 0;
純粋仮想は「実装見て〜」で済ませられないので、通常のmethod以上にcommentの必要性は高いですね。

2019-11-06 01:52 UTC, gotakamikubo commented on the_destination_of_shadow/Draw.cpp
> +VOID Texture::Animetion(INT * flamecount, INT count, FLOAT * tu, FLOAT * tv, FLOAT split_tu, FLOAT split_tv, FLOAT start_tu, FLOAT start_tv, FLOAT finish_tu, FLOAT finish_tv)
この関数の改良は別issueで作業します。
作り直す可能性が高いですが。

2019-11-06 01:53 UTC, gotakamikubo commented on the_destination_of_shadow/Game.h
> +	VOID Loading();
読み込みはLoadingというイメージでしたのでこの名前にしています。

2019-11-06 01:59 UTC, taishi-matsumura commented on the_destination_of_shadow/Draw.cpp
> +VOID Texture::Animetion(INT * flamecount, INT count, FLOAT * tu, FLOAT * tv, FLOAT split_tu, FLOAT split_tv, FLOAT start_tu, FLOAT start_tv, FLOAT finish_tu, FLOAT finish_tv)
過去の制作からの流用コードなのですね。了解です。
issue切っておいて下さい。

2019-11-06 02:17 UTC, gotakamikubo commented on the_destination_of_shadow/Draw.h
> +	FLOAT m_y_size;
修正しました

2019-11-06 02:44 UTC, gotakamikubo commented on the_destination_of_shadow/Draw.cpp
> +DOUBLE Texture::to_Rad(DOUBLE degree)
修正しました

2019-11-06 02:45 UTC, gotakamikubo commented on the_destination_of_shadow/Draw.h
> +enum TEX
修正しました

2019-11-06 02:45 UTC, gotakamikubo commented on the_destination_of_shadow/Draw.h
> +struct XyCoordinate
修正しました

2019-11-06 02:45 UTC, gotakamikubo commented on the_destination_of_shadow/Draw.h
> +struct UvCoordinate
修正しました

2019-11-06 02:57 UTC, gotakamikubo commented on the_destination_of_shadow/Game.h
> +	VOID Loading();
しかしこれだけ動名詞なのはおかしいので修正します

2019-11-07 09:37 UTC, gotakamikubo commented on the_destination_of_shadow/Game.cpp
> +	player.texture.Draw(player.GetXyCoordinate());
修正しました

2019-11-07 09:37 UTC, gotakamikubo commented on the_destination_of_shadow/Draw.cpp
> +VOID Texture::LoadTexture(const CHAR * file_name, INT TEX)
修正しました

2019-11-07 09:37 UTC, gotakamikubo commented on the_destination_of_shadow/Draw.cpp
>  	return degree * atan(1.0)* 4.0 / 180.0;
過去の制作の流用です

2019-11-07 09:38 UTC, gotakamikubo commented on the_destination_of_shadow/Character.h
> +	virtual VOID Move() = 0;
了解です

2019-11-07 10:37 UTC, gotakamikubo commented on the_destination_of_shadow/Object.h
> +	XyCoordinate GetXyCoordinate() { return xy_coordinate; }
了解です

2019-11-08 07:43 UTC, taishi-matsumura approved these changes
もうひと押し！
今回の指摘を直したらもう良さそうなので、approveしておきます。
あとはコミットを整理してからmergeしてもらって下さい。

2019-11-08 07:43 UTC, taishi-matsumura commented on the_destination_of_shadow/Character.h
> +	* @brief キャラクターの動作、エネミーならAI、プレイヤーなら動作に関する処理を書く
書くとするなら
```suggestion
	* @brief キャラクターを動かす
	* @note 各派生クラスにて、動作に関する処理をimplementすること
```
とかかなぁ。
briefに書く内容では無いですね。

2019-11-08 07:43 UTC, taishi-matsumura commented on the_destination_of_shadow/Object.h
> +	inline XyCoordinate GetXyCoordinate()const { return xy_coordinate; }
`const` の前後にspace入れましょう

2019-11-08 07:43 UTC, taishi-matsumura commented on the_destination_of_shadow/Draw.cpp
>  	return degree * atan(1.0)* 4.0 / 180.0;
ってことは、理由は不明ということですね？
うーん、イケてない… 👎

2019-11-08 07:56 UTC, gotakamikubo commented on the_destination_of_shadow/Object.h
> +	inline XyCoordinate GetXyCoordinate()const { return xy_coordinate; }
了解です

2019-11-08 07:56 UTC, gotakamikubo commented on the_destination_of_shadow/Character.h
> +	* @brief キャラクターの動作、エネミーならAI、プレイヤーなら動作に関する処理を書く
noteの存在を忘れてました。
修正します

2019-11-08 08:49 UTC, merged