[WIP]現実世界と影の世界の切り替え
human-osaka-game-2019/The_Destination_Of_Shadow pull request #36
Opened 2019-11-08 04:33 UTC by MinoriNakamura

close #25 

## 作業
- [ ] 二つの世界をAボタンで切り替える

2019-11-11 08:52 UTC, gotakamikubo requested changes
取りあえず

2019-11-11 08:52 UTC, gotakamikubo commented on the_destination_of_shadow/Game.cpp
> +	player.LoadTexture("../Texture/shadow_background.png", SHADOW_BACKGROUND);
プレイヤーで背景画像をロードはちょっと...

2019-11-11 08:52 UTC, gotakamikubo commented on the_destination_of_shadow/Game.cpp
> +		player.m_uses_mirror = true;
trueも大文字で

2019-11-11 11:03 UTC, taishi-matsumura requested changes
ヘッダファイルincludeの順序やdoxygenコメントは常に意識して下さいね。

2019-11-11 11:03 UTC, taishi-matsumura commented on the_destination_of_shadow/Background.cpp
> +#include "Background.h"
ガイドライン貼っときますので確認お願いします。
不明点があれば質問して下さい。
https://ttsuki.github.io/styleguide/cppguide.ja.html#Names_and_Order_of_Includes

2019-11-11 11:03 UTC, taishi-matsumura commented on the_destination_of_shadow/Background.h
> +class RealBackground :public Object
新規追加時にdoxygenコメント入れてしまいましょう。
後から直すのは大変ですよ。

2019-11-11 11:03 UTC, taishi-matsumura commented on the_destination_of_shadow/Background.h
> +	RealBackground();
publicメンバにはコメント入れましょう。

2019-11-11 11:03 UTC, taishi-matsumura commented on the_destination_of_shadow/Game.cpp
> +	{
この2つのif文は同時に成立することは無いですよね？
であれば if-else if にするか、switch-caseにしましょう。

2019-11-11 11:03 UTC, taishi-matsumura commented on the_destination_of_shadow/Game.cpp
> +		shadow_background.Draw(shadow_background.texture.GetUvCoordinate(), SHADOW_BACKGROUND);
詳細見ていませんが、polymorphismを用いて共通化できませんか？

2019-11-11 11:03 UTC, taishi-matsumura commented on the_destination_of_shadow/Game.h
> +	ShadowBackground shadow_background;
この辺のメンバ変数、なぜpublic？

2019-11-11 11:03 UTC, taishi-matsumura commented on the_destination_of_shadow/Player.h
> +	BOOL m_uses_mirror;
変数名、個人的には好きですが他の人は `m_is_mirror_used` の方がわかりやすいかも知れませんね。
まぁ、チームで判断して下さい。

2019-11-12 06:42 UTC, MinoriNakamura commented on the_destination_of_shadow/Game.h
> +	ShadowBackground shadow_background;
すみません、仮置きでした...。
ゲームシーンでしか使用しませんし、早いことprivateにします。

2019-11-12 06:51 UTC, MinoriNakamura commented on the_destination_of_shadow/Background.h
> +class RealBackground :public Object
わかりました。
これからは作成と同時に記載します。

2019-11-12 07:28 UTC, MinoriNakamura commented on the_destination_of_shadow/Player.h
> +	BOOL m_uses_mirror;
チームで話し合ったのですが、m_uses_mirroのままでいこうと思います。
ご意見ありがとうございます。

2019-11-12 07:28 UTC, MinoriNakamura commented on the_destination_of_shadow/Game.cpp
> +	{
swichに修正します。

2019-11-12 07:28 UTC, MinoriNakamura commented on the_destination_of_shadow/Background.h
> +	RealBackground();
追記します。

2019-11-12 07:29 UTC, MinoriNakamura commented on the_destination_of_shadow/Game.cpp
> +	player.LoadTexture("../Texture/shadow_background.png", SHADOW_BACKGROUND);
すみません、修正します。

2019-11-12 07:29 UTC, MinoriNakamura commented on the_destination_of_shadow/Game.cpp
> +		player.m_uses_mirror = true;
わかりました。

2019-11-12 08:15 UTC, MinoriNakamura commented on the_destination_of_shadow/Background.cpp
> +#include "Background.h"
確認し、変更しました。

2019-11-13 02:03 UTC, MinoriNakamura commented on the_destination_of_shadow/Game.cpp
> +		shadow_background.Draw(shadow_background.texture.GetUvCoordinate(), SHADOW_BACKGROUND);
すみませんスケジュールに遅れが生じているため、少しすぐの修正は検討させてください。

2019-11-13 02:23 UTC, taishi-matsumura commented on the_destination_of_shadow/Game.cpp
> +		shadow_background.Draw(shadow_background.texture.GetUvCoordinate(), SHADOW_BACKGROUND);
了解です。issue切っておいて下さい。

2019-11-13 02:27 UTC, taishi-matsumura commented on the_destination_of_shadow/Player.h
> +	BOOL m_uses_mirror;
👍

2019-11-13 02:33 UTC, taishi-matsumura commented on the_destination_of_shadow/Game.h
> +	Game::SCENE_PAHSE phase = Game::LOAD;
コメント。

2019-11-13 05:33 UTC, MinoriNakamura commented on the_destination_of_shadow/Game.h
> +	Game::SCENE_PAHSE phase = Game::LOAD;
そちらのコメントはResult、Helpとも一気に記載したいのでこのブランチではなく修正用ブランチでまとめて記載する予定です。

2019-11-13 15:05 UTC, taishi-matsumura commented on the_destination_of_shadow/Game.h
> +	Game::SCENE_PAHSE phase = Game::LOAD;
了解です 👌 
issueやpull request作ったら、そいつらのdescriptionにこのpull requestへのリンクを貼っておくと相互にtraceできるはずなので、そのようにお願いします。

2019-11-14 04:19 UTC, gotakamikubo approved these changes
修正確認しました

2019-11-14 09:37 UTC, MinoriNakamura commented on the_destination_of_shadow/Game.cpp
> +		shadow_background.Draw(shadow_background.texture.GetUvCoordinate(), SHADOW_BACKGROUND);
すみません、遅れましたがissue作成しました

2019-11-14 09:37 UTC, MinoriNakamura commented on the_destination_of_shadow/Game.h
> +	Game::SCENE_PAHSE phase = Game::LOAD;
pull requestも作成しました

2019-11-14 09:38 UTC, taishi-matsumura approved these changes
指摘是正は別issue/別pull requestで対応予定とのことですので、こちらはapproveしておきます。
コミットを整理したらmergeして貰って下さい。

2019-11-15 07:10 UTC, merged