[WIP]DirectXクラスに存在するpublicなメンバ変数をカプセル化
human-osaka-game-2019/The_Destination_Of_Shadow pull request #38
Opened 2019-11-08 10:14 UTC by gotakamikubo

closes #33 
## 作業
- [ ] publicなメンバ構造体をprivateへ移動

- [ ] 必要なゲッター関数を作成

2019-11-14 07:31 UTC, MinoriNakamura requested changes

2019-11-14 07:31 UTC, MinoriNakamura commented on the_destination_of_shadow/Xinput.h
> +#include <Xinput.h>
インクルードの順番がおかしいです
それと、Xinput.hは作ったヘッダーのはずです

2019-11-14 07:31 UTC, MinoriNakamura commented on the_destination_of_shadow/Xinput.h
> +
関数の下のスペースは開けないように統一しましょう

2019-11-14 07:31 UTC, MinoriNakamura commented on the_destination_of_shadow/DirectX.h
>  #include <tchar.h>
alphabeticalにしてほしいです

2019-11-14 07:31 UTC, MinoriNakamura commented on the_destination_of_shadow/Game.cpp
関数始まりのスペースもなしでお願いします

2019-11-14 09:20 UTC, gotakamikubo commented on the_destination_of_shadow/Xinput.h
> +#include <Xinput.h>
そこでincludeしているのは元々あったもので自分が作成したものではないです
紛らわしい名前にしてしまって申し訳ないです

2019-11-14 09:20 UTC, gotakamikubo commented on the_destination_of_shadow/DirectX.h
>  #include <tchar.h>
了解です

2019-11-14 09:27 UTC, gotakamikubo commented on the_destination_of_shadow/Game.cpp
了解です

2019-11-14 09:27 UTC, gotakamikubo commented on the_destination_of_shadow/Xinput.h
> +
了解です

2019-11-14 10:19 UTC, MinoriNakamura commented on the_destination_of_shadow/Xinput.h
> +#include <Xinput.h>
わかりました。
それなら大丈夫です。

2019-11-15 04:27 UTC, MinoriNakamura approved these changes

2019-11-15 04:28 UTC, merged