[WIP]自機の移動
human-osaka-game-2019/The_Destination_Of_Shadow pull request #6
Opened 2019-10-18 08:17 UTC by MinoriNakamura

#5 

- [ ] Characterクラスを作成

- [ ] CharacterクラスをPlayerクラス、Enemyクラスに継承

- [ ] それらを使い、自機の移動をする

2019-10-25 06:48 UTC, taishi-matsumura requested changes
publicなメンバをゼロにするようにしなきゃなのに、増やしてどうする。

2019-10-25 06:48 UTC, taishi-matsumura commented on the_destination_of_shadow/DirectX.h
> +	GamePadDeadZone game_pad_dead_zone;
カプセル化して下さい

2019-10-25 07:08 UTC, gotakamikubo requested changes
class名、コーディング規約が守られていません

2019-10-25 07:11 UTC, gotakamikubo reviewed
class名確認漏れでしたすみません

2019-10-25 08:11 UTC, MinoriNakamura commented on the_destination_of_shadow/DirectX.h
> +	GamePadDeadZone game_pad_dead_zone;
変更しました

2019-10-25 08:37 UTC, gotakamikubo approved these changes
確認しました

2019-10-28 08:09 UTC, gotakamikubo reviewed
ちょっとした指摘です

2019-10-28 08:09 UTC, gotakamikubo commented on the_destination_of_shadow/Player.cpp
> +	m_TEX = PLAYER;
メンバ変数なのでTexなのでは

2019-10-28 08:10 UTC, gotakamikubo commented on the_destination_of_shadow/Player.cpp
> +	m_TEX = PLAYER;
すみませんm_texでした

2019-10-28 08:12 UTC, MinoriNakamura commented on the_destination_of_shadow/Player.cpp
> +	m_TEX = PLAYER;
enumだったので大文字にしていましたが、m_texのほうが綺麗だと思いました。
修正します。

2019-10-29 00:02 UTC, gotakamikubo approved these changes
変更確認しました

2019-10-29 08:28 UTC, taishi-matsumura requested changes
まだapproveできないですねー

2019-10-29 08:28 UTC, taishi-matsumura commented on the_destination_of_shadow/Enemy.h
> +};
改行入れといて下さい

2019-10-29 08:28 UTC, taishi-matsumura commented on the_destination_of_shadow/Character.h
> +class CharacterBase
doxygenコメントは？
上久保にも指摘しましたが、
* 自作の型
* 各列挙子
* publicメンバ

にはコメント入れましょう。

2019-10-29 08:28 UTC, taishi-matsumura commented on the_destination_of_shadow/Character.h
> +	virtual VOID Move()=0;
これ、publicでは？

2019-10-29 08:28 UTC, taishi-matsumura commented on the_destination_of_shadow/Player.cpp
> +
不要な改行は消しましょう。他も同様。

2019-10-29 08:28 UTC, taishi-matsumura commented on the_destination_of_shadow/Player.cpp
> +	if (directx.XinputState.Gamepad.sThumbLX >= DEAD_ZONE_RIGHT)
`.` で繋ぎ過ぎ。

2019-10-29 08:28 UTC, taishi-matsumura commented on the_destination_of_shadow/Player.h
> +#include "Character.h"
alphabeticalにsortして下さい。他も同様。

2019-10-29 08:28 UTC, taishi-matsumura commented on the_destination_of_shadow/Player.h
> +*/
インデントおかしいです

2019-10-29 08:28 UTC, taishi-matsumura commented on the_destination_of_shadow/Character.h
> +class CharacterBase
基底クラスに仮想デストラクタを書いていない理由があれば教えて下さい。
逆に、追加するように修正するのであればその理由も教えて下さい。

2019-10-29 09:01 UTC, taishi-matsumura commented on the_destination_of_shadow/DirectX.h
> +	GamePadDeadZone game_pad_dead_zone;
publicなメンバが残っていて企業さんから突っ込まれた先輩がたくさん居ます。
頑張って撲滅して下さいね。

2019-10-30 06:18 UTC, MinoriNakamura commented on the_destination_of_shadow/Enemy.h
> +};
すぐに修正します

2019-10-30 06:23 UTC, MinoriNakamura commented on the_destination_of_shadow/Character.h
> +class CharacterBase
確認漏れでした、修正します

2019-10-30 06:44 UTC, MinoriNakamura commented on the_destination_of_shadow/Player.cpp
> +
改行、削除しました

2019-10-30 06:45 UTC, MinoriNakamura commented on the_destination_of_shadow/Player.h
> +*/
修正しました

2019-10-30 07:10 UTC, taishi-matsumura approved these changes
指摘是正は基本的にα後にすると伺いましたので、とりあえずapproveしておきます。
指摘に対するissue作って(纏めない方が良いと思います)対応していってくださーい 💪

2019-11-01 16:14 UTC, merged