影を借りる処理、影を使用する処理を一部実装
human-osaka-game-2019/The_Destination_Of_Shadow pull request #61
Opened 2019-12-05 06:34 UTC by gotakamikubo

#40 #41 #42 #59 
## 概要
上記のissueの内容をこのPullRequestで実装する

- [ ] ＃４０

- [ ] ＃４１

- [ ] ＃４２

- [ ] ＃５９

2019-12-05 06:36 UTC, gotakamikubo commented
優先順位の変化によりこのPullRequestを閉じ、マージ後優先順位が高い作業が終わり次第
新たにPullRequestを出します

2019-12-05 15:19 UTC, MinoriNakamura requested changes

2019-12-05 15:19 UTC, MinoriNakamura commented on the_destination_of_shadow/Shadow.cpp
> +}
改行をお願いします。

2019-12-05 15:19 UTC, MinoriNakamura commented on the_destination_of_shadow/Shadow.h
> +	Shadow(XyCoordinate gimmick, XyCoordinate cursor);
一応コメントがあったほうが良い気がします。

2019-12-06 07:14 UTC, gotakamikubo commented on the_destination_of_shadow/Shadow.cpp
> +}
了解です

2019-12-06 07:28 UTC, gotakamikubo commented on the_destination_of_shadow/Shadow.h
> +	Shadow(XyCoordinate gimmick, XyCoordinate cursor);
了解です

2019-12-06 16:33 UTC, MinoriNakamura approved these changes

2019-12-08 14:11 UTC, merged